
name: binaries

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - id: install-things
      run: pip install -Ur bin-requirements.txt

    - id: pyinstaller-ldogger
      run: |
        ./setup.py --version || exit 1
        pyinstaller -n ldogger-linux-x86_64 --specpath contrib/ --onedir --noconfirm --log-level INFO ./run-ldogger.py

    - id: pyinstaller-sj2l
      run: |
        ./setup.py --version || exit 1
        pyinstaller -n sj2l-linux-x86_64 --specpath contrib/ --onedir --noconfirm --log-level INFO ./sj2l.py

    - uses: actions/upload-artifact@v3
      with:
        name: ldogger-linux-x86_64
        path: dist/ldogger-linux-x86_64

    - uses: actions/upload-artifact@v3
      with:
        name: sj2l-linux-x86_64
        path: dist/sj2l-linux-x86_64

    - id: check-versions
      run: |
        ./dist/ldogger-linux-x86_64 --version
        ./dist/sj2l-linux-x86_64 --version
