
name: binaries

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    # use of a really old container to roll back that base glibc verison.
    # pythons compiled for older glibc work just fine on newer ones, but not
    # the reverse
    container: jettero/kersplat:1.0.27
    env:
      PATH: /usr/local/pyenv/bin:/usr/local/pyenv/shims:/bin:/sbin:/usr/bin:/usr/sbin
      PYENV_ROOT: /usr/local/pyenv

    strategy:
      matrix:
        bin:
          - name: ldogger
            file: run-ldogger.py
          - name: sj2l
            file: sj2l.py

    steps:
      - uses: actions/checkout@v2
          # can't use git describe without tags... fetch-depth: 0 tells checkout to get tags (and things)
        with:
          fetch-depth: 0

      - run: pip install -U pip wheel
      - run: pip install -U setuptools_scm
      - run: pip install -Ur bin-requirements.txt

      - run: 'git tag -l | grep -v ^v[0-9] | xargs -rn1 git tag -d'
      - run: ./setup.py --version
      - run: |
          pyinstaller -n ${{ matrix.bin.name }}-linux-x86_64 \
            --specpath contrib/ --onefile --noconfirm --log-level INFO \
            ./${{ matrix.bin.file }}
      - run: ./dist/${{ matrix.bin.name }}-linux-x86_64 --version

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.bin.name }}-linux-x86_64
          path: dist/${{ matrix.bin.name }}-linux-x86_64
