
name: binaries

on:
  workflow_call:
    inputs: {}
  workflow_dispatch:
    inputs: {}

jobs:
  sj2l:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - id: install-things
      run: pip install -Ur bin-requirements.txt

    - id: pyinstaller
      run: pyinstaller --specpath contrib/ --onedir --noconfirm --log-level INFO ./sj2l.py

    - uses: actions/upload-artifact@v3
      with:
        name: sj2l
        path: dist/sj2l
