
name: release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  call-binaries:
    uses: ./.github/workflows/binaries.yaml
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: call-binaries
    steps:
      - run: git describe | sed -e 's/\([0-9]\)-g/\1-/g'
