
name: release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - run: ls -al ./.github/workflows
    - uses: ./.github/workflows/pyinstaller.yaml
      # with:
        #  varname: valuehere
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sj2l"
        token: ${{ secrets.GITHUB_TOKEN }}
