
name: release

on:
  push:
    tags:
      - v*.*.*-?*
  workflow_dispatch:
    inputs: {}

jobs:
  binaries:
    uses: ./.github/workflows/binaries.yaml
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: binaries
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: ldogger-linux-x86_64
          path: .
      - uses: actions/download-artifact@v3
        with:
          name: sj2l-linux-x86_64
          path: .
      - run: chmod 0755 *-linux-x86_64
      - run: ./ldogger-linux-x86_64 --version | sed -e 's/\+g[0-9a-f][0-9a-f]*//' | tee ver.txt

      - name: create release
        run: |
          ver="$(< ver.txt)"
          ghrc_args=( --generate-notes )

          if [[ "$ver" =~ ([.]dev|-rc) ]]
          then ghrc_args+=( -p )
          fi

          if [[ "$ver" =~ ^v?[0-9][0-9]*.[0-9][0-9]*.[0-9][0-9]* ]]; then
              if [[ "$ver" =~ ^v ]]
              then tag=$ver
              else tag=v$ver
              fi
              ghrc_args+=( -t "$ver" $tag )
          else
              echo abort here to avoid creating an annoying tag and release name
              exit 1
          fi

          gh release delete -y "$tag" &>/dev/null || :
          gh release create "${ghrc_args[@]}" sj2l-linux-x86_64 ldogger-linux-x86_64

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
