
name: release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  call-binaries:
    uses: ./github/workflows/binaries@${{ github.sha }}
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: call-binaries
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sj2l"
        token: ${{ secrets.GITHUB_TOKEN }}
